### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by reactmore** [rezafikkri/School-website#1]
Fatal error: Call to a member function result() on boolean in /storage/emulated/0/htdocs/sisbw/application/models/Model_galeri.php on line 44

Kiranya kenapa ya ? 
PHP 7,3

**Comment by rezafikkri** [comment]
Sepertinya saya tidak menemukan error yang kamu maksud, saya menggunakan php7.3.20.

**Comment by rezafikkri** [comment]
Mungkin kamu harus clone atau fork lagi repo-nya.
