### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jooirvt** [rezafikkri/School-website#4]
Fatal error: Maximum execution time of 120 seconds exceeded in C:\xampp\htdocs\smk\system\core\Common.php on line 597
A PHP Error was encountered
Severity: Error

Message: Maximum execution time of 120 seconds exceeded

Filename: core/Common.php

Line Number: 597

Backtrace:

Berikut ini line 597; 
function _error_handler($severity, $message, $filepath, $line)
	{
		$is_error = (((E_ERROR | E_PARSE | E_COMPILE_ERROR | E_CORE_ERROR | E_USER_ERROR) & $severity) === $severity);

Kira-kira kenapa min?

**Comment by rezafikkri** [comment]
emm, mungkin settingan di php.ini nya, coba tambahin max_execution_time di file php.ini nya.
